import { Account, Category, Txn, BudgetPlan, RecurringRule, Goal, AppSettings } from '../types';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-bca',
    name: 'BCA Utama',
    type: 'bank',
    currency: 'IDR',
    opening_balance: 14500000,
    icon: 'Landmark',
    color: '#0F172A',
    is_archived: false,
    created_at: Date.now() - 30 * 86400000,
    updated_at: Date.now(),
  },
  {
    id: 'acc-gopay',
    name: 'GoPay',
    type: 'ewallet',
    currency: 'IDR',
    opening_balance: 385000,
    icon: 'Smartphone',
    color: '#334155',
    is_archived: false,
    created_at: Date.now() - 30 * 86400000,
    updated_at: Date.now(),
  },
  {
    id: 'acc-cash',
    name: 'Uang Tunai',
    type: 'cash',
    currency: 'IDR',
    opening_balance: 240000,
    icon: 'Banknote',
    color: '#059669',
    is_archived: false,
    created_at: Date.now() - 30 * 86400000,
    updated_at: Date.now(),
  },
  {
    id: 'acc-shopeepay',
    name: 'ShopeePay',
    type: 'ewallet',
    currency: 'IDR',
    opening_balance: 115000,
    icon: 'CreditCard',
    color: '#475569',
    is_archived: false,
    created_at: Date.now() - 30 * 86400000,
    updated_at: Date.now(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Pengeluaran (Clean Elegant Monochrome Slate)
  { id: 'cat-makan', name: 'Makan & Minum', kind: 'expense', icon: 'Utensils', color: '#1E293B', sort_order: 1 },
  { id: 'cat-trans', name: 'Transportasi', kind: 'expense', icon: 'Car', color: '#1E293B', sort_order: 2 },
  { id: 'cat-belanja', name: 'Belanja Harian', kind: 'expense', icon: 'ShoppingBag', color: '#1E293B', sort_order: 3 },
  { id: 'cat-tagihan', name: 'Tagihan & Utilitas', kind: 'expense', icon: 'Receipt', color: '#1E293B', sort_order: 4 },
  { id: 'cat-hiburan', name: 'Hiburan & Hobi', kind: 'expense', icon: 'Film', color: '#1E293B', sort_order: 5 },
  { id: 'cat-kesehatan', name: 'Kesehatan', kind: 'expense', icon: 'HeartPulse', color: '#1E293B', sort_order: 6 },
  { id: 'cat-pendidikan', name: 'Pendidikan', kind: 'expense', icon: 'GraduationCap', color: '#1E293B', sort_order: 7 },
  { id: 'cat-lainnya', name: 'Lainnya', kind: 'expense', icon: 'CircleEllipsis', color: '#64748B', sort_order: 8 },
  // Pemasukan (Signature Forest Emerald)
  { id: 'cat-gaji', name: 'Gaji Pokok', kind: 'income', icon: 'Briefcase', color: '#059669', sort_order: 1 },
  { id: 'cat-bonus', name: 'Bonus & Freelance', kind: 'income', icon: 'BadgeDollarSign', color: '#059669', sort_order: 2 },
  { id: 'cat-invest', name: 'Hasil Investasi', kind: 'income', icon: 'TrendingUp', color: '#059669', sort_order: 3 },
  { id: 'cat-hadiah', name: 'Hadiah / Cashback', kind: 'income', icon: 'Gift', color: '#059669', sort_order: 4 },
];

const now = Date.now();
const day = 86400000;

export const INITIAL_TRANSACTIONS: Txn[] = [
  // Drafts (Inbox) per PRD FR-25, 7.3
  {
    id: 'txn-draft-1',
    type: 'expense',
    amount: 35000,
    account_id: 'acc-gopay',
    category_id: 'cat-makan',
    merchant: 'Soto Betawi Bang Ali',
    occurred_at: now - 35 * 60000,
    note: 'Makan siang sama teman kantor',
    status: 'draft',
    source: 'voice',
    confidence: 0.92,
    raw_source_text: '"Makan siang soto betawi 35 ribu pakai GoPay"',
    created_at: now - 35 * 60000,
    updated_at: now - 35 * 60000,
  },
  {
    id: 'txn-draft-2',
    type: 'expense',
    amount: 54500,
    account_id: 'acc-bca',
    category_id: 'cat-belanja',
    merchant: 'Indomaret Point Sudirman',
    occurred_at: now - 3 * 3600000,
    note: 'Roti, susu oat, air mineral',
    status: 'draft',
    source: 'ocr',
    confidence: 0.88,
    external_ref: 'IND-994182',
    raw_source_text: 'Foto Struk Kasir Indomaret Point total Rp 54.500',
    created_at: now - 3 * 3600000,
    updated_at: now - 3 * 3600000,
  },
  {
    id: 'txn-draft-3',
    type: 'expense',
    amount: 22000,
    account_id: 'acc-gopay',
    category_id: 'cat-trans',
    merchant: 'Gojek Ride',
    occurred_at: now - 6 * 3600000,
    note: 'Transport ke kantor pagi',
    status: 'draft',
    source: 'notification',
    confidence: 0.96,
    external_ref: 'GK-88271',
    raw_source_text: 'Notifikasi: Pembayaran GoRide berhasil Rp 22.000 ke Gojek',
    created_at: now - 6 * 3600000,
    updated_at: now - 6 * 3600000,
  },

  // Confirmed transactions
  {
    id: 'txn-conf-1',
    type: 'expense',
    amount: 25000,
    account_id: 'acc-gopay',
    category_id: 'cat-makan',
    merchant: 'Kopi Kenangan',
    occurred_at: now - 5 * 3600000,
    note: 'Kopi Kenangan Mantan Large',
    status: 'confirmed',
    source: 'qr',
    confidence: 0.99,
    created_at: now - 5 * 3600000,
    updated_at: now - 5 * 3600000,
  },
  {
    id: 'txn-conf-2',
    type: 'expense',
    amount: 14000,
    account_id: 'acc-bca',
    category_id: 'cat-trans',
    merchant: 'MRT Jakarta',
    occurred_at: now - 7 * 3600000,
    note: 'Tap in Bundaran HI - Blok M',
    status: 'confirmed',
    source: 'manual',
    created_at: now - 7 * 3600000,
    updated_at: now - 7 * 3600000,
  },
  {
    id: 'txn-conf-3',
    type: 'expense',
    amount: 185000,
    account_id: 'acc-bca',
    category_id: 'cat-tagihan',
    merchant: 'PLN Pascabayar',
    occurred_at: now - 1 * day,
    note: 'Listrik kos bulanan',
    status: 'confirmed',
    source: 'ocr',
    external_ref: 'PLN-202610-09',
    created_at: now - 1 * day,
    updated_at: now - 1 * day,
  },
  {
    id: 'txn-conf-4',
    type: 'expense',
    amount: 45000,
    account_id: 'acc-cash',
    category_id: 'cat-makan',
    merchant: 'Warung Nasi Padang',
    occurred_at: now - 1 * day - 4 * 3600000,
    note: 'Ayam pop + es teh manis',
    status: 'confirmed',
    source: 'manual',
    created_at: now - 1 * day - 4 * 3600000,
    updated_at: now - 1 * day - 4 * 3600000,
  },
  {
    id: 'txn-conf-5',
    type: 'income',
    amount: 9500000,
    account_id: 'acc-bca',
    category_id: 'cat-gaji',
    merchant: 'PT Solusi Teknologi',
    occurred_at: now - 4 * day,
    note: 'Gaji Oktober 2026',
    status: 'confirmed',
    source: 'sms',
    external_ref: 'BCA-SAL-1026',
    created_at: now - 4 * day,
    updated_at: now - 4 * day,
  },
  {
    id: 'txn-conf-6',
    type: 'transfer',
    amount: 500000,
    account_id: 'acc-bca',
    to_account_id: 'acc-gopay',
    occurred_at: now - 3 * day,
    note: 'Top up GoPay jajan',
    status: 'confirmed',
    source: 'manual',
    admin_fee: 1000,
    created_at: now - 3 * day,
    updated_at: now - 3 * day,
  },
  {
    id: 'txn-conf-7',
    type: 'expense',
    amount: 120000,
    account_id: 'acc-bca',
    category_id: 'cat-hiburan',
    merchant: 'Cinema XXI',
    occurred_at: now - 2 * day,
    note: 'Nonton film 2 tiket + popcorn',
    status: 'confirmed',
    source: 'manual',
    created_at: now - 2 * day,
    updated_at: now - 2 * day,
  },
];

export const INITIAL_BUDGET: BudgetPlan = {
  id: 'budget-active-1',
  method: 'category',
  period: 'monthly',
  start_day: 1,
  is_active: true,
  total_limit: 5500000,
  lines: [
    { id: 'b-line-1', category_id: 'cat-makan', name: 'Makan & Minum', amount: 2000000, rollover: true },
    { id: 'b-line-2', category_id: 'cat-trans', name: 'Transportasi', amount: 750000, rollover: false },
    { id: 'b-line-3', category_id: 'cat-belanja', name: 'Belanja Harian', amount: 1000000, rollover: false },
    { id: 'b-line-4', category_id: 'cat-tagihan', name: 'Tagihan & Utilitas', amount: 950000, rollover: false },
    { id: 'b-line-5', category_id: 'cat-hiburan', name: 'Hiburan & Hobi', amount: 500000, rollover: false },
    { id: 'b-line-6', category_id: 'cat-kesehatan', name: 'Kesehatan', amount: 300000, rollover: true },
  ],
};

export const INITIAL_RECURRING: RecurringRule[] = [
  {
    id: 'rec-netflix',
    name: 'Netflix Premium',
    type: 'expense',
    amount: 186000,
    account_id: 'acc-bca',
    category_id: 'cat-hiburan',
    frequency: 'monthly',
    day_of_month: 15,
    next_run_at: now + 7 * day,
    mode: 'auto',
    is_active: true,
    is_subscription: true,
  },
  {
    id: 'rec-bpjs',
    name: 'BPJS Kesehatan Mandiri',
    type: 'expense',
    amount: 150000,
    account_id: 'acc-bca',
    category_id: 'cat-kesehatan',
    frequency: 'monthly',
    day_of_month: 10,
    next_run_at: now + 2 * day,
    mode: 'draft',
    is_active: true,
    is_subscription: true,
  },
  {
    id: 'rec-cicilan',
    name: 'Cicilan Gadget (iPhone)',
    type: 'expense',
    amount: 1250000,
    account_id: 'acc-bca',
    category_id: 'cat-tagihan',
    frequency: 'monthly',
    day_of_month: 25,
    next_run_at: now + 17 * day,
    mode: 'draft',
    is_active: true,
    total_tenor: 12,
    remaining_tenor: 5,
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-emergency',
    name: 'Dana Darurat 6 Bulan',
    target_amount: 20000000,
    saved_amount: 14500000,
    account_id: 'acc-bca',
    due_at: now + 120 * day,
    auto_amount: 1000000,
  },
  {
    id: 'goal-bali',
    name: 'Liburan Akhir Tahun Bali',
    target_amount: 6000000,
    saved_amount: 3200000,
    account_id: 'acc-bca',
    due_at: now + 75 * day,
    auto_amount: 750000,
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  currency: 'IDR',
  start_day: 1,
  theme: 'light',
  pin_enabled: false,
  biometrics_enabled: true,
  onboarding_completed: true,
  auto_confirm_trusted: false,
  view_mode: 'ios_frame',
};
