import React from 'react';
import {
  Utensils,
  Car,
  ShoppingBag,
  Receipt,
  Film,
  HeartPulse,
  GraduationCap,
  CircleEllipsis,
  Briefcase,
  BadgeDollarSign,
  TrendingUp,
  Gift,
  Landmark,
  Smartphone,
  Banknote,
  CreditCard,
  Plus,
  Mic,
  Camera,
  QrCode,
  SlidersHorizontal,
  Home,
  ListOrdered,
  PiggyBank,
  MoreHorizontal,
  ShieldCheck,
  Download,
  Upload,
  RefreshCw,
  Search,
  Check,
  X,
  AlertCircle,
  HelpCircle,
  ArrowRightLeft,
  ChevronRight,
  Clock,
  Sparkles,
  Percent,
  Calendar,
  Lock,
  Unlock,
  KeyRound,
  FileSpreadsheet,
  Moon,
  Sun,
  Eye,
  EyeOff,
  Bell,
  LucideProps,
} from 'lucide-react';

const iconMap: Record<string, React.FC<LucideProps>> = {
  Utensils,
  Car,
  ShoppingBag,
  Receipt,
  Film,
  HeartPulse,
  GraduationCap,
  CircleEllipsis,
  Briefcase,
  BadgeDollarSign,
  TrendingUp,
  Gift,
  Landmark,
  Smartphone,
  Banknote,
  CreditCard,
  Plus,
  Mic,
  Camera,
  QrCode,
  SlidersHorizontal,
  Home,
  ListOrdered,
  PiggyBank,
  MoreHorizontal,
  ShieldCheck,
  Download,
  Upload,
  RefreshCw,
  Search,
  Check,
  X,
  AlertCircle,
  HelpCircle,
  ArrowRightLeft,
  ChevronRight,
  Clock,
  Sparkles,
  Percent,
  Calendar,
  Lock,
  Unlock,
  KeyRound,
  FileSpreadsheet,
  Moon,
  Sun,
  Eye,
  EyeOff,
  Bell,
};

export const getIconComponent = (name: string, fallback = CircleEllipsis): React.FC<LucideProps> => {
  return iconMap[name] || fallback;
};

export const AppIcon: React.FC<{ name: string; className?: string; size?: number }> = ({
  name,
  className = 'w-5 h-5',
  size = 20,
}) => {
  const Icon = getIconComponent(name);
  return <Icon className={className} size={size} />;
};
